# Basic dependabot.yml file with
# minimum configuration for one package manager

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every month
    schedule:
      interval: 'monthly'
    # Set limit on amount of opened PRs with deps updates to 5
    open-pull-requests-limit: 5
    # Set the target branch
    target-branch: 'develop'
    # Set labels
    labels:
      - 'npm'
      - 'dependencies'
    # Set reviewers
    reviewers:
      - 'bolotskyDev'
      # Set assignees
    assignees:
      - 'bolotskyDev'
