version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: node_modules/.bin/gatsby develop --host=0.0.0.0
    ports:
      - 8100:8000
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
