import { Heading } from 'components/shared/heading';
import React from 'react';

import styles from './overview.module.scss';

export const ExtensionsOverview = () => (
  <section className={`container ${styles.container}`}>
    <Heading tag={'h2'} size={'lg'} className={styles.title}>
      What are k6 extensions?
    </Heading>

    <p className={styles.description}>
      k6 extensions allow for functionality not natively supported within k6.
      These standalone Go projects can take advantage of internal Go APIs to
      provide new functionality to support your specific reliability testing
      needs.
    </p>

    <p className={styles.description}>
      Currently supported extensions come in two different forms:
      <ul>
        <li>
          <em>JavaScript extensions</em> - enhance JavaScript APIs available to
          your test scripts. Add support for new network protocols, improve
          performance compared to equivalent JS libraries, or provide features
          not supported by the k6 core.
        </li>
        <li>
          <em>Output extensions</em> - enable support for customized handling of
          metric data generated by k6. These extensions receive test metrics
          from k6 to allow further processing or dispatching.
        </li>
      </ul>
    </p>
  </section>
);
