#!/usr/bin/env bash

function usage {
  cat <<EOF
Apply the changes for directory SRC for commit COMMIT to directory DST.
The script assumes it is run from the root of the repository.

Usage:
  $0 <COMMIT> <SRC> <DST>

Examples:
  $0 HEAD~ docs/sources/next docs/sources/v0.47.x
EOF
}

TMPDIR=$(mktemp -d)

if [[ $# -ne 3 ]]; then
  usage
  exit 1
fi

case "${@}" in
  --help | -h)
    usage
    exit 0
    ;;
  *)
esac

COMMIT="$1"
SRC="$2"
DST="$3"

PATCH="${TMPDIR}/diff.patch"

# path_components returns the number of leading path components to strip from traditional diff paths.
function path_components {
  local p="$1"
  local -i n=2

  if [[ "${p}" =~ "/$" ]]; then
    n=1
  fi

  while [[ "${p}" =~ "/" ]]; do
    (( n++ ))
    p="${p%/*}"
  done

  echo "${n}"
}

GIT_ROOT="$(git rev-parse --show-toplevel)"
if [[ "$(pwd)" != "${GIT_ROOT}" ]]; then
  echo "ERROR: Script has not been run from the repository root ('${GIT_ROOT}')."
  echo "Please change directory there and adjust argument paths to match the new working directory."

  exit 1
fi

git diff "${COMMIT}" -- "${SRC}" > "${PATCH}"
git apply -p "$(path_components "${SRC}")" --directory "${DST}" "${PATCH}"
