"exceptions":
  - "Amazon ARN"
  - "Amazon CloudWatch"
  - "Amazon Data Firehose"
  - "Amazon Elastic Kubernetes Service"
  - "Amazon Firehose"
  - "Amazon Kinesis"
  - "Amazon Relational Database Service"
  - "Amazon SSM"
  - "ADOT"
  - "AI Observability"
  - "Agent"
  - "Alloy"
  - "ARN"
  - "Asserts"
  - "AWS"
  - "AWS Distro for OpenTelemetry Collector"
  - "AWS X-Ray"
  - "Beyla"
  - "BoringCrypto"
  - "CentOS"
  - "CloudWatch"
  - "Codespaces"
  - "Data Firehose"
  - "Databricks"
  - "Datadog"
  - "Dynatrace"
  - "EKS"
  - "Elastic Kubernetes Service"
  - "Entra"
  - "Figma"
  - "Firehose"
  - "FreeBSD"
  - "GEM"
  - "GKE"
  - "Git"
  - "GitHub"
  - "GitLab"
  - "GNU"
  - "Grafana"
  - "Gravatar"
  - "Graylog"
  - "Gunicorn"
  - "hashmod"
  - "IBM"
  - "InfluxDB"
  - "Jaeger"
  - "Jira"
  - "JMESPath"
  - "journald"
  - "Jsonnet"
  - "Kibana"
  - "Killercoda"
  - "Kinesis"
  - "Kotlin"
  - "KQL"
  - "Kubernetes"
  - "Kubernetes Engine"
  - "Kusto"
  - "Kustomize"
  - "LangChain"
  - "launchd"
  - "Logs Drilldown"
  - "Loki"
  - "Lucene"
  - "Markdown"
  - "Memcached"
  - "Metrics Drilldown"
  - "Mesos"
  - "Mimir"
  - "Moodle"
  - "MySQL"
  - "Netlink"
  - "Okta"
  - "OnCall"
  - "OpenAI"
  - "OpenShift"
  - "OpenTelemetry"
  - "Opsgenie"
  - "OTel"
  - "PagerDuty"
  - "Parca"
  - "Phlare"
  - "Pinecone"
  - "Podman"
  - "Postgres"
  - "PostgreSQL"
  - "pprof"
  - "Profiles Drilldown"
  - "Prometheus"
  - "Promtail"
  - "Pyroscope"
  - "RCA workbench"
  - "RDS"
  - "Relational Database Service"
  - "React"
  - "Redis"
  - "RHEL"
  - "Rollup"
  - "RudderStack"
  - "Sensu"
  - "Sensu Go"
  - "Splunk"
  - "SSM"
  - "SUSE"
  - "Tempo"
  - "Thanos"
  - "Threema"
  - "Traces Drilldown"
  - "Velero"
  - "Vite"
  - "VMware"
  - "Webex"
  - "WildFly"
  - "windows_exporter"
  - "YugabyteDB"
  - "Zipkin"
  - "ACL"
  - "ADOT"
  - "API"
  - "APT"
  - "ARN"
  - "AWS"
  - "BPF"
  - "CDN"
  - "CLA"
  - "CLI"
  - "CLS"
  - "CMS"
  - "CORS"
  - "CPU"
  - "CRD"
  - "CSS"
  - "CSV"
  - "DNS"
  - "DOM"
  - "eBPF"
  - "EKS"
  - "FAQ"
  - "FCP"
  - "FID"
  - "GEM"
  - "GKE"
  - "GNU"
  - "GPG"
  - "GPU"
  - "GUI"
  - "HTML"
  - "HTTP"
  - "HTTPS"
  - "IBM"
  - "ICU"
  - "IDE"
  - "JAR"
  - "JPG"
  - "JSON"
  - "JSX"
  - "KEDA"
  - "KPI"
  - "LCP"
  - "LESS"
  - "LLM"
  - "NAT"
  - "OSS"
  - "OTLP"
  - "PDF"
  - "PHP"
  - "PLZ"
  - "PNG"
  - "PVC"
  - "RAM"
  - "RBAC"
  - "RDS"
  - "RED"
  - "REPL"
  - "RHEL"
  - "RPM"
  - "RSA"
  - "SCM"
  - "SCSS"
  - "SDK"
  - "SEO"
  - "SHA-1"
  - "SLA"
  - "SLI"
  - "SLO"
  - "SQL"
  - "SRE"
  - "SSD"
  - "SSM"
  - "SSH"
  - "SSL"
  - "SSO"
  - "SUSE"
  - "SUT"
  - "SVG"
  - "TCP"
  - "TLS"
  - "TSDB"
  - "TTL"
  - "UI"
  - "UID"
  - "URI"
  - "URL"
  - "USB"
  - "UTC"
  - "UTF"
  - "UUID"
  - "UX"
  - "VPC"
  - "VU"
  - "VUH"
  - "WAL"
  - "XML"
  - "XSS"
  - "YAML"
  - "ZIP"
  - "Application Programming Interface"
  - "Advanced package tool"
  - "Amazon Web Services"
  - "Berkeley Packet Filter"
  - "Content Delivery Network"
  - "Contributor License Agreement"
  - "Cumulative Layout Shift"
  - "Custom Resource Definition"
  - "Cascading Style Sheets"
  - "Comma-separated values"
  - "Document Object Model"
  - "Elastic Kubernetes Service"
  - "First Contentful Paint"
  - "First Input Delay"
  - "Grafana Enterprise Metrics"
  - "Google Kubernetes Engine"
  - "HyperText Markup Language"
  - "HyperText Transfer Protocol"
  - "HyperText Transfer Protocol Secure"
  - "International Components for Unicode"
  - "Kubernetes-based Event-Driven Autoscaling"
  - "Largest Contentful Paint"
  - "Leaner Style Sheets"
  - "OpenTelemetry Protocol"
  - "Portable Document Format"
  - "PHP: Hypertext Preprocessor"
  - "Private Load Zone"
  - "Portable Network Graphics"
  - "Persistent Volume Claim"
  - "Role-based Access Control"
  - "Relational Database Service"
  - "RPM Package Manager"
  - "Rivest–Shamir–Adleman"
  - "Sassy CSS"
  - "Secure Hash Algorithm 1"
  - "Structured Query Language"
  - "Secure Shell"
  - "Secure Sockets Layer"
  - "System Under Test"
  - "Scalable Vector Graphics"
  - "Transmission Control Protocol"
  - "Transport Layer Security"
  - "Uniform Resource Identifier"
  - "Uniform Resource Locator"
  - "Universal Serial Bus"
  - "Coordinated Universal Time"
  - "Unicode Transformation Format"
  - "Extensible Markup Language"
  - "YAML Ain't Markup Language"
  - "Adaptive Metrics"
  - "Ansible"
  - "Application Observability"
  - "AWS Observability"
  - "AzureAD"
  - "Beyla"
  - "BoltDB"
  - "Cloud Logs"
  - "Cloud Metrics"
  - "Cloud Traces"
  - "Cluster"
  - "Frontend Observability"
  - "Generic OAuth"
  - "GitHub"
  - "GitLab"
  - "Google"
  - "GKE Autopilot"
  - "Grafana"
  - "Grafana Agent"
  - "Grafana Agent Flow"
  - "Grafana Cloud"
  - "Grafana Cloud Traces"
  - "Grafana Enterprise Logs"
  - "Grafana Enterprise Metrics"
  - "Grafana Enterprise Traces"
  - "Grafana Labs"
  - "Graylog"
  - "Helm"
  - "Hugo"
  - "IBM Cloud"
  - "Kibana"
  - "Kubernetes Monitoring"
  - "LogQL"
  - "Loki"
  - "macOS"
  - "Memcached"
  - "Microsoft"
  - "Mimir"
  - "Node Exporter"
  - "OAuth"
  - "Okta"
  - "OpenCost"
  - "OpenTelemetry"
  - "OpenTelemetry Collector"
  - "Personally Identifiable Information"
  - "Prometheus"
  - "PromQL"
  - "Promtail"
  - "Pyroscope"
  - "Redis"
  - "Service Level Objective"
  - "Tempo"
  - "Terraform"
  - "Thanos"
  - "TraceQL"
  - "WebSockets"
  - "What's new"
  - "Writers' Toolkit"
  - "YouTube"
"extends": "capitalization"
"level": "warning"
"link": "https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings"
"match": "$sentence"
"message": |
  Use sentence-style capitalization for '%s'.

  Vale considers multi-word exceptions such as _Grafana Enterprise Metrics_ as a single correctly cased word.

  If your heading contains capitalized words that represent product names, you need to add those words to the Grafana dictionary or the list of static exceptions in https://github.com/grafana/writers-toolkit/blob/main/vale/Headings.jsonnet for them to be considered correctly cased.
"scope": "heading"
"threshold": 0.3
