"action":
  "name": "replace"
"extends": "substitution"
"ignorecase": false
"level": "warning"
"link": "https://grafana.com/docs/writers-toolkit/write/style-guide/word-list/"
"message": "Use '%s' instead of '%s'."
"swap":
  "(?:(?<!Data )Firehose|Kinesis Data Firehose|Kinesis Firehose)": "Data Firehose"
  "(?:SHA-1|HAS-SHA1)": "SHA-1"
  "(?:WiFi|wifi)": "Wi-Fi"
  "(?:[Oo]penshift|openShift)": "OpenShift"
  "(?:[eE]-mail)": "email"
  "(?:[jJ][mM][eE][sS]p|jmesP)ath": "JMESPath"
  "(?:[oO]pentelemetry|openTelemetry)": "OpenTelemetry"
  "(?:alert[Mm]anager|[Aa]lert [Mm]anager|AlertManager)": "Alertmanager"
  "(?:cell ?phone|smart ?phone)": "phone|mobile phone"
  "(?:content|media)-?type": "media type"
  "(?:file ?path|path ?name)": "path"
  "(?:file ?path|path ?name)s": "paths"
  "(?:github|gitHub|Github)": "GitHub"
  "(?:gitlab|gitLab|Gitlab)": "GitLab"
  "(?:hamburger menu|kebab menu)": "menu icon"
  "(?:java[Ss]cript|Javascript)": "JavaScript"
  "(?:kill|terminate|abort)": "stop|exit|cancel|end"
  "(?<!kube-)prometheus": "Prometheus"
  "(?<!lambda-)promtail": "Promtail"
  "GME": "GEM"
  "Grafana AI observability": "Grafana AI Observability"
  "HTTPs": "HTTPS"
  "Influx[Dd]b": "InfluxDB"
  "Influxd[Bb]": "InfluxDB"
  "Once": "After"
  "Pagerduty": "PagerDuty"
  "RCA Workbench": "RCA workbench"
  "Rudderstack": "RudderStack"
  "VMWare": "VMware"
  "Vmware": "VMware"
  "[Ww]orld [Ww]ide [Ww]eb": "web"
  "[cC]entos": "CentOS"
  "\\b(?:[aA]daptive metrics|adaptive Metrics)\\b": "Adaptive Metrics"
  "ad[- ]?hoc": "free-form|user-written"
  "back[ -]end": "backend"
  "blacklist": "blocklist"
  "blacklisted": "blocklisted"
  "blacklisting": "blocklisting"
  "blacklists": "blocklists"
  "cadvisor": "cAdvisor"
  "check[- ]box": "checkbox"
  "content type": "media type"
  "data-?source": "data source"
  "data-?sources": "data sources"
  "data[- ]?set": "dataset"
  "data[- ]?sets": "datasets"
  "datacenter": "data center"
  "datacenters": "data centers"
  "de-duplicate": "deduplicate"
  "de-duplicated": "deduplicated"
  "de-duplicates": "deduplicates"
  "de-duplication": "deduplication"
  "fewer data": "less data"
  "figma": "Figma"
  "file name": "filename"
  "file names": "filenames"
  "firewalls": "firewall rules"
  "front[ -]end": "frontend"
  "front[ -]ends": "frontends"
  "git": "Git"
  "grafana": "Grafana"
  "grayed-out": "unavailable"
  "gunicorn": "Gunicorn"
  "in order to": "to"
  "influx[Dd][Bb]": "InfluxDB"
  "jsonnet": "Jsonnet"
  "kotlin": "Kotlin"
  "langchain": "LangChain"
  "left[- ]hand[- ]side": "left-side"
  "log(?:ql|QL)": "LogQL"
  "loki": "Loki"
  "lucene": "Lucene"
  "markdown": "Markdown"
  "memcached": "Memcached"
  "meta[- ]data": "metadata"
  "mix[- ]in": "mixin"
  "mysql": "MySQL"
  "network IP address": "internal IP address"
  "open-source": "open source"
  "otel": "OTel"
  "otlp": "OTLP"
  "pager[dD]uty": "PagerDuty"
  "phlare": "Phlare"
  "postgres": "Postgres"
  "postgresql": "PostgreSQL"
  "prom(?:ql|QL)": "PromQL"
  "redis": "Redis"
  "regex[ep]?s": "regular expression"
  "regexp?": "regular expression"
  "repo": "repository"
  "repos": "repositories"
  "right[- ]hand[- ]side": "right-side"
  "rudderstack": "RudderStack"
  "sensu": "Sensu"
  "sign into": "sign in to"
  "sqlite": "SQLite"
  "style sheet": "stylesheet"
  "style sheets": "stylesheet"
  "synch": "sync"
  "synched": "synced"
  "synching": "syncing"
  "tempo": "Tempo"
  "the Grafana Agent": "Grafana Agent"
  "the RCA [Ww]orkbench": "RCA workbench"
  "threema": "Threema"
  "timeseries": "time series|time-series"
  "trace(?:ql|QL)": "TraceQL"
  "un(?:check|select)": "clear"
  "url": "URL"
  "urls": "URLs"
  "vmware": "VMware"
  "vs\\.": "versus"
  "webex": "Webex"
  "whitelist": "allowlist"
  "whitelisted": "allowlisted"
  "whitelisting": "allowlisting"
  "whitelists": "allowlists"
  "yugabyte": "YugabyteDB"
