name: Pull Request CI

env:
  PATH_PREFIX: /docs/${{ github.ref }}
  GATSBY_JOB_COUNTER: ${{ secrets.CI_GATSBY_JOB_COUNTER }}
  GATSBY_DEFAULT_MAIN_URL: https://staging.k6.io
  GATSBY_DEFAULT_DOC_URL: https://mdr-ci.staging.k6.io/docs/${{ github.ref }}
  GATSBY_DEFAULT_BLOG_URL: https://k6.io/blog
  GATSBY_DEFAULT_APP_URL: https://app.staging.k6.io

on:
  pull_request:
    branches: main

jobs:
  update-dependencies:
    name: Update node module dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Use Node.js 15.xs
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
  lint:
    name: Lint code and prose
    needs: [update-dependencies]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Use Node.js 15.xs
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Install vale
        run: |
          curl -sfL https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh -s v2.4.0
          export PATH="./bin:$PATH"
          vale -v
      - name: Lint code
        run: |
          npm run lint
      - name: Lint prose
        run: |
          export PATH="./bin:$PATH"
          npm run lint:prose
  build:
    name: Build pull request
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2

      - name: Print build settings
        run: |
          echo "PATH_PREFIX: $PATH_PREFIX"
          echo "GATSBY_DEFAULT_MAIN_URL: $GATSBY_DEFAULT_MAIN_URL"
          echo "GATSBY_DEFAULT_DOC_URL: $GATSBY_DEFAULT_DOC_URL"
          echo "GATSBY_DEFAULT_BLOG_URL: $GATSBY_DEFAULT_BLOG_URL"
          echo "GATSBY_DEFAULT_APP_URL: $GATSBY_DEFAULT_APP_URL"

      - name: Use Node.js 15.xs
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: k6-docs
          path: public/
          retention-days: 1

  deploy:
    name: Deploy pull request
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.PR_CI_AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PR_CI_AWS_SECRET_KEY }}
      AWS_REGION: 'eu-west-1'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: k6-docs
          path: public/

      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.PR_CI_AWS_S3_BUCKET }}
          SOURCE_DIR: public/
          DEST_DIR: docs/${{ github.ref }}

      - name: Invalidate Cloudfront
        uses: chetan/invalidate-cloudfront-action@v1.2
        env:
          DISTRIBUTION: ${{ secrets.PR_CI_CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/docs/*'

      - name: Post published URL to PR
        if: github.event.action == 'opened'
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.payload.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body:
                "There's a version of the docs published here:\n\n" +
                `${process.env.GATSBY_DEFAULT_DOC_URL}\n\n` +
                'It will be deleted automatically in 30 days.',
            })
