# This workflow prevents users from manually changing the
# docs/sources/next/extensions/explore.md file.

# Changes to the registry should only be made automatically
# by the extension-registry-changed workflow.

name: Prevent file change
on:
  pull_request:
    types: [opened, reopened]
    paths:
        - 'docs/k6/**/extensions/explore.md'

permissions:
  pull-requests: read

jobs:
  prevent-file-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        with:
          persist-credentials: false
        uses: actions/checkout@v4

      - name: Prevent manual changes to the extension registry file
        uses: xalvarez/prevent-file-change-action@v2
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          pattern: .*\extensions/explore\.md
          trustedAuthors: heitortsergent, szkiba, pablochacin, andrewslotin, mstoykov, inancgumus, oleiade, ankur22, codebien, joanlopez, AgnesToulet
          allowNewFiles: true # To prevent issues when we release a new version of k6
