name: publish-technical-documentation-k6-studio

on:
  push:
    branches:
      - main
    paths:
      - "docs/sources/k6-studio/**"
  workflow_dispatch:
jobs:
  sync:
    if: github.repository == 'grafana/k6-docs'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/writers-toolkit/publish-technical-documentation@publish-technical-documentation/v1
        with:
          source_directory: docs/sources/k6-studio
          website_directory: content/docs/k6-studio
