name: Remove old artifacts

on:
  schedule:
    # Every day at 10:00 UTC
    - cron: '0 10 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '3 day'
